"""Initial payment service tables

Revision ID: e6ce106be786
Revises: 
Create Date: 2026-03-13 10:30:38.640602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ce106be786'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('bank_transfer', 'momo_qr', name='payment_methods'), nullable=False),
    sa.Column('pg_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'expired', name='payment_transaction_statuses'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('payment_data_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pg_transaction_id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_id'))

    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
